### ISSUE TITLE
Detect from Picture  error！

### ISSUE THREAD

**Issue by freemde23** [nonnonstop/sd-webui-3d-open-pose-editor#30] opened 2023-03-28 03:42 UTC
TypeError: Cannot read properties of undefined (reading 'map') at i2.DetectFromImage (http://127.0.0.1:7860/file=R:/stable-diffusion-webui/extensions/sd-webui-3d-open-pose-editor/javascript/lazy/main.js:28054:40)

**Comment by nonnonstop** [comment] 2023-03-28 04:19
Maybe same as #18.
I think the error is that the pose cannot be recognized from the image. Could you try another image?

**Comment by freemde23** [comment] 2023-03-28 11:18
> Maybe same as #18. I think the error is that the pose cannot be recognized from the image. Could you try another image?

tested 6 images, all this Error

the same image can be identified on this website, perhaps with reference to its code?

**Comment by nonnonstop** [comment] 2023-04-01 05:09
Duplicate of #18

**Closed by nonnonstop** 2023-04-01 05:09 UTC
Labels: bug
