### ISSUE TITLE
Can't detect from the image

### ISSUE THREAD

**Issue by JiaChen-Zeng** [nonnonstop/sd-webui-3d-open-pose-editor#34] opened 2023-03-30 05:42 UTC
It worked before but now it's broken. I don't know what affected it.

```
TypeError: Cannot read properties of undefined (reading 'map') at i2.DetectFromImage (http://127.0.0.1:7860/file=extensions/sd-webui-3d-open-pose-editor/javascript/lazy/main.js?c7969a7a:28054:40)
```

**Comment by nonnonstop** [comment] 2023-04-01 05:11
Duplicate of #18.

The pose cannot be recognized from the image.
If you get an error with any image, please post the image you used.

**Closed by nonnonstop** 2023-04-01 05:11 UTC
